### ISSUE TITLE
packet queue is empty, aborting

### ISSUE THREAD

**Issue by cChimney** [h0nde/py-hcaptcha#10]
been trying this out for a lil bit but getting packet queue is empty, aborting, any idea what that is?

**Comment by h0nde** [comment]
sounds like a redis-related error. do you have redis installed and running on your local address?

**Comment by cChimney** [comment]
Yea i do and i have not gotten that error again for some reason, can u add me on tg or disc btw got some questions. cChimney#5193 and @cChimney.

**Comment by PaPaTrolls** [comment]
why did you link ur github is this supposed to be joke or? out of curious.

**Comment by cChimney** [comment]
@ cChimney is my telegram like i said

**Comment by 4tkn148** [comment]
> 
> 
> sounds like a redis-related error. do you have redis installed and running on your local address?

this fixed my problem thanks
