### ISSUE TITLE
Issue while using the solver

### ISSUE THREAD

**Issue by Andrea-Miele** [h0nde/py-hcaptcha#11]
i get this issue while using the solver
```
    sio.connect("http://localhost:9932")
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\socketio\client.py", line 338, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
```

**Comment by h0nde** [comment]
I'm not sure about this one. May I have the full code that you're running?

**Comment by Andrea-Miele** [comment]
It's the code written in the README file

**Comment by poky1084** [comment]
Possible that the server is already running or the port is busy or taken, also install all Python packages if thats the case
Try closing all python.exe in Task Manager

**Comment by Chr0nicT** [comment]
> I'm not sure about this one. May I have the full code that you're running?

Also getting this issue:
Python 3.10.0
```python
import hcaptcha

ch = hcaptcha.Challenge(
    site_key="13257c82-e129-4f09-a733-2a7cb3102832",
    site_url="https://dashboard.hcaptcha.com/",
    #proxy="user:pass@127.0.0.1:8888",
    #ssl_context=__import__("ssl")._create_unverified_context(),
    timeout=5
)

if ch.token:
    print(ch.token)
    exit()

print(ch.question["en"])

for tile in ch:
    image = tile.get_image(raw=False)
    image.show()
    if input("answer (y/n): ").lower() == "y":
        ch.answer(tile)

try:
    token = ch.submit()
    print(token)
except hcaptcha.ChallengeError as err:
    print(err)
```

**Comment by BigDaddyRBX** [comment]
> Possible that the server is already running or the port is busy or taken, also install all Python packages if thats the case Try closing all python.exe and py.exe in Task Manager

It doesn't have to do anything with port, if it was port issue it should respond "port is  already in use", 

I've runned with this issue.
