### ISSUE TITLE
Hcaptcha bypass/solver information ;)

### ISSUE THREAD

**Issue by cChimney** [h0nde/py-hcaptcha#18]
Yo can u add me on telegram @ cChimney or discord cChimney#1337,
i got some nice information to make a cap bypass/solver out of but you know more about solvers so i need ur opinions n shit on it. I'll explain more if u add me. Thanks

**Comment by fritzhaxx** [comment]
ass

**Comment by cChimney** [comment]
u a bish

**Comment by cChimney** [comment]
ratio
