### ISSUE TITLE
Issue using Solving, and Usage  sample codes in Readme.md

### ISSUE THREAD

**Issue by poky1084** [h0nde/py-hcaptcha#8]
Hi, 
I donwloaded the repo and installed required packages to Python 3.9.6
I ran the two sample codes separately and got two thing.

When I ran the Usage code i got this error in the console:

```
File "C:\Users\dev\Downloads\py-hcaptcha-main\py-hcaptcha-main\build\lib\test.py", line 11, in <module>
    print(ch.question["en"])
TypeError: 'NoneType' object is not subscriptable

```
After testing the second Solving code, i got repeatedly this:

```
StopIteration()
StopIteration()
StopIteration()
StopIteration()
StopIteration()
StopIteration()
StopIteration()
StopIteration()
....
```

Both tries the Chrome window pops up and prints OK.

**Comment by h0nde** [comment]
The first issue might be because you got a pre-solved challenge.

The second issue might be because your proxies.txt doesn't have a sufficient amount of proxies for your thread/worker count.

**Comment by poky1084** [comment]
Thanks! Work fine now. I had presolved captcha. Does the Solving work without proxies? I tried with one proxy and without any proxies too, that it would work with home IP. 
I appreciate your work!

**Comment by poky1084** [comment]
Does the presovled challenge was due to the Accesibiltiy cookie? Does it detect the cookie? I didnt see in the source any cookie codes, this is why i asked

**Comment by h0nde** [comment]
Creating large amounts of challenges using a single IP is just not possible, so proxies are pretty much required.

The library doesn't make use of accessibility cookies. Some websites have a lower level of security and may blindly accept the library's requests.

**Comment by poky1084** [comment]
I wrote a code based on py-hcaptcha, that is using hs_accessibilty cookie. It passes the cookie to the 3rd party website's captcha. It can be used as e.g login captcha bypass for sites with hcaptcha.

[hc_accessibility.zip](https://github.com/h0nde/py-hcaptcha/files/7453556/hc_accessibility.zip)
